SCREEN_WIDTH = 800
SCREEN_HEIGHT =600

PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50

MOVE_SPEED = 35
DROP_SPEED = 10
PLAYER_START_POSITION = (SCREEN_WIDTH/2-PLAYER_WIDTH/2,SCREEN_HEIGHT-PLAYER_HEIGHT)

INTRO_IMG_WIDTH = 200
INTRO_IMG_HEIGHT = 200

